language: php

cache:
  directories:
    - $COMPOSER_CACHE_DIR

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls
